## NumPy
NumPy stands for Numerical Python & is the core library for nummeric & scientific computing
It consists of Multidimensional Array objects & a colllection of routines for processing those arrays

In [2]:
import numpy as np

# Single Dimensional Array

In [9]:
n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

# Multi Dimensional Array

In [12]:
n2 = np.array([[10,20,30,40],[50,60,70,80]])
n2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

# Array with Element Zero and Same Number


In [18]:
# array with all elements zero
n3 = np.zeros((3,4))
n3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
# array with all elements with same number
n4 = np.full((3,4),5)
n4

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

# Array with elements in a range of number

In [4]:
n5 = np.arange(10,20,2)
n5

array([10, 12, 14, 16, 18])

# Array with random numbers

In [6]:
n6 = np.random.randint(1,100,10)
n6

array([81, 79, 19, 68, 67, 94, 32,  9, 27, 49])

In [7]:
n7 = np.random.randint(1,10,size=(3,4))
n7

array([[1, 4, 6, 5],
       [8, 2, 4, 5],
       [3, 8, 5, 3]])

# Checking shape of array


In [15]:
n7.shape

(3, 4)

In [16]:
n7.shape = (4,3)
n7.shape

(4, 3)

In [17]:
n7

array([[1, 4, 6],
       [5, 8, 2],
       [4, 5, 3],
       [8, 5, 3]])

# Joining Numpy Arrays

In [19]:
## Vertical Stack
n1 = np.array([10,20,30,40,50])
n2 = np.array([1,2,3,4,5])
np.vstack((n2,n1))

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [20]:
## Horizontal Stack
np.hstack((n1,n2))

array([10, 20, 30, 40, 50,  1,  2,  3,  4,  5])

In [21]:
## Column Stack
np.column_stack((n1,n2))

array([[10,  1],
       [20,  2],
       [30,  3],
       [40,  4],
       [50,  5]])

# Intersection & Difference


In [22]:
n1 = np.array([10,20,30,40,50])
n2 = np.array([40,50,60,70,20])
np.intersect1d(n1,n2)

array([20, 40, 50])

In [23]:
np.union1d(n1,n2)

array([10, 20, 30, 40, 50, 60, 70])

In [25]:
np.setdiff1d(n1,n2)


array([10, 30])

In [26]:
np.setdiff1d(n2,n1)

array([60, 70])

# Sum of Two Arrays


In [28]:
n1=np.array([10,20])
n2=np.array([30,40])
np.sum([n1,n2])

100

In [29]:
np.sum([n1,n2],axis=0)
# Column Sum

array([40, 60])

In [30]:
np.sum([n1,n2],axis=1)
# Row Sum

array([30, 70])

In [34]:
np.diff([n1,n2],axis=0)

array([[20, 20]])

In [35]:
np.diff([n1,n2],axis=1)

array([[10],
       [10]])

# Mathematical Operations

In [37]:
n1=np.array([10,20])
n1=n1+1
n1

array([11, 21])

In [39]:
n1=np.array([10,20])
n1=n1-1
n1

array([ 9, 19])

In [40]:
n1=np.array([10,20])
n1=n1*2
n1

array([20, 40])

In [42]:
n1=np.array([10,20])
n1=n1//2
n1

array([ 5, 10])

In [45]:
n1=np.array([10,20,30,40,50])
np.mean(n1)

30.0

In [46]:
np.median(n1)

30.0

In [47]:
np.std(n1)

14.142135623730951

# Transpose

In [49]:
n2 = np.array([[10,20,30,40],[50,60,70,80]])
n2[0]

array([10, 20, 30, 40])

In [50]:
n2[1]

array([50, 60, 70, 80])

In [51]:
n2[:,0]

array([10, 50])

In [52]:
n2[:,2]

array([30, 70])

In [53]:
n2.transpose()

array([[10, 50],
       [20, 60],
       [30, 70],
       [40, 80]])

In [54]:
np.save('my array',n2)

In [55]:
n3=np.load('my array.npy')
n3

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])